---
apiVersion: v1
kind: Secret
metadata:
  name: resource-db-secret
  namespace: ktask
type: Opaque
stringData:
  POSTGRES_PASSWORD: "1111"
  DB_HOST: "resource-db"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "1111"

---
apiVersion: v1
kind: Secret
metadata:
  name: song-db-secret
  namespace: ktask
type: Opaque
stringData:
  POSTGRES_PASSWORD: "1111"
  DB_HOST: "song-db"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "1111"
