apiVersion: v1
kind: Service
metadata:
  name: resource-db
  namespace: ktask
spec:
  type: ClusterIP
  selector:
    app: resource-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: song-db
  namespace: ktask
spec:
  type: ClusterIP
  selector:
    app: song-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432