apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ktask
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-db
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/init-resource-svc-db.sql
              subPath: init-resource-svc-db.sql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/init-song-svc-db.sql
              subPath: init-song-svc-db.sql
      volumes:
        - name: initdb
          configMap:
            name: postgres-initdb-config
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: postgres-db
      spec:
        storageClassName: hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi