apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-svc
  namespace: ktask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-svc
  template:
    metadata:
      labels:
        app: resource-svc
    spec:
      containers:
        - name: resource-svc
          image: irrisorrimus/resource-svc
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: resource-db-secret
          env:
            - name: SONG_SVC
              value: "song-svc"
          ports:
            - containerPort: 8071