apiVersion: v1
kind: Service
metadata:
  name: resource-svc
  namespace: ktask
spec:
  type: ClusterIP
  selector:
    app: resource-svc
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
#  clusterIP: None