apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-svc
  namespace: ktask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-svc
  template:
    metadata:
      labels:
        app: song-svc
    spec:
      containers:
        - name: song-svc
          image: irrisorrimus/song-svc
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: song-db-secret
          ports:
            - containerPort: 8072