apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-user-service
  namespace: user-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-user-service
  template:
    metadata:
      labels:
        app: alpine-user-service
    spec:
      containers:
        - name: alpine
          image: alpine
          command: ["/bin/sh", "-ec", "while :; do echo 'Hello!'; sleep 5; done"]
          volumeMounts:
            - name: alpine-data
              mountPath: /usr/share/alpine-data
      volumes:
        - name: alpine-data
          persistentVolumeClaim:
            claimName: user-service-pvc
