apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-pvc
  namespace: user-task
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Mi
