apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-service-pv
  namespace: user-task
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/user-service" # will be created inside the Docker Desktop VM